export HB_PATH=/usr/local # Homebrew env path
export NVM_DIR="$HOME/.nvm" 
. "$HB_PATH/opt/nvm/nvm.sh" # nvm path

# Make brew local the default local
export PATH=$HB_PATH/bin:$HB_PATH/sbin:~/bin:$PATH

# Syslink for coreutils
export PATH="$(brew --prefix coreutils)/libexec/gnubin:$HB_PATH/bin:$PATH"

# GNU manpages for programs that are GNU ones, and fallback to OSX manpages otherwise
alias man='_() { echo $1; man -M $(brew --prefix)/opt/coreutils/libexec/gnuman $1 1>/dev/null 2>&1;  if [ "$?" -eq 0 ]; then man -M $(brew --prefix)/opt/coreutils/libexec/gnuman $1; else man $1; fi }; _'

# Auto-complete for bash
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

# Better git support
if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
  __GIT_PROMPT_DIR=$(brew --prefix)/opt/bash-git-prompt/share
  source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
fi

# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

source ~/.profile

export GOPATH=$HOME/Development/learning
export PATH=$PATH:$GOPATH/bin

export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$PATH:/path/to/elixir/bin"

